######################################################################
# Automatically generated by qmake (3.0) wt. maj 8 15:47:14 2018
######################################################################

TEMPLATE = app
TARGET = RExpediter
INCLUDEPATH += .

# Input
HEADERS += menu.h
SOURCES += menu.cpp RExpediter.cpp

include (./common.pri)

